### ISSUE TITLE
[Bug Report] Not displaying properly in Multiplayer

### ISSUE THREAD

**Issue by burritosoftware** [ckosmic/CustomEnergyBars#1]
In Multiplayer mode, the selected custom energy bar flips upside down.

**Comment by ckosmic** [comment]
So far I've been unable to replicate this, but another user has also let me know of this bug.  Can you send me a list of your mods so I can check for incompatibilities?  Also I recognize you from the jailbreaking scene haha

**Comment by burritosoftware** [comment]
[Here's a hastebin with mods](https://hastebin.com/uhebariset.css)

Also yeah, I retired from that scene way long ago though since it was kinda harsh and toxic, but I still jailbreak my own devices.

**Comment by ckosmic** [comment]
It turns out it was a problem with MultiplayerExtensions when Vertical HUD is enabled.  I've submitted a PR just now that fixes it: https://github.com/Zingabopp/MultiplayerExtensions/pull/127
