### ISSUE TITLE
Add option to hide energy bar

### ISSUE THREAD

**Issue by Kakifrucht** [ckosmic/CustomEnergyBars#4]
Would be nice to have!

**Comment by ANewDawn** [comment]
+1 Would like to hide energy bar as don't use it and prefer not have it shown

**Comment by ckosmic** [comment]
Here's an empty energy bar: https://cdn.discordapp.com/attachments/848052328324923432/902007908735262760/Empty_Bar.energy

**Comment by Kakifrucht** [comment]
Works perfectly, thank you!
